// Mock data for DepartmentService
import { Department } from '../models/department.model';

export const MOCK_DEPARTMENTS: Department[] = [
    // BI層（最高層，通常1-3個）
    {
        deptId: 1,
        parentDeptId: null,
        deptCode: 'CORP',
        deptName: '企業發展事業群',
        deptLevel: 'BI',
        managerEmpId: 1,
        isActive: true,
        deptDesc: '負責公司整體發展與決策，涵蓋策略與規劃等。',
        createTime: '2024-01-10T08:00:00',
        createUser: 'sysadmin',
        updateTime: '2024-06-01T08:30:00',
        updateUser: 'sysadmin',
        parentDeptName: undefined,
        managerName: '林泰安'
    },
    {
        deptId: 2,
        parentDeptId: null,
        deptCode: 'TECH',
        deptName: '技術策略事業群',
        deptLevel: 'BI',
        managerEmpId: 2,
        isActive: true,
        deptDesc: '主導技術方向與產品創新策略。',
        createTime: '2024-01-12T09:00:00',
        createUser: 'sysadmin',
        updateTime: '2024-06-03T09:45:00',
        updateUser: 'sysadmin',
        parentDeptName: undefined,
        managerName: '張偉翔'
    },
    // BU 層
    {
        deptId: 3,
        parentDeptId: 1,
        deptCode: 'OPS',
        deptName: '營運管理中心',
        deptLevel: 'BU',
        managerEmpId: 3,
        isActive: true,
        deptDesc: '統籌營運資源，確保業務穩定發展。',
        createTime: '2024-02-01T10:00:00',
        createUser: 'admin1',
        updateTime: '2024-06-08T10:00:00',
        updateUser: 'admin1',
        parentDeptName: '企業發展事業群',
        managerName: '蘇怡君'
    },
    {
        deptId: 4,
        parentDeptId: 1,
        deptCode: 'SALE',
        deptName: '銷售服務中心',
        deptLevel: 'BU',
        managerEmpId: 4,
        isActive: true,
        deptDesc: '負責全公司銷售目標與客戶關係管理。',
        createTime: '2024-02-02T13:00:00',
        createUser: 'admin2',
        updateTime: '2024-06-10T13:00:00',
        updateUser: 'admin2',
        parentDeptName: '企業發展事業群',
        managerName: '高家豪'
    },
    {
        deptId: 5,
        parentDeptId: 2,
        deptCode: 'ENG',
        deptName: '工程研發中心',
        deptLevel: 'BU',
        managerEmpId: 5,
        isActive: true,
        deptDesc: '技術開發與產品維護的核心部門。',
        createTime: '2024-02-03T11:00:00',
        createUser: 'admin3',
        updateTime: '2024-06-11T11:00:00',
        updateUser: 'admin3',
        parentDeptName: '技術策略事業群',
        managerName: '許惠玲'
    },
    // 添加更多部門以達到測試數量...
    // LOB 層示例
    {
        deptId: 7,
        parentDeptId: 3,
        deptCode: 'CUST',
        deptName: '客服組',
        deptLevel: 'LOB-S',
        managerEmpId: 7,
        isActive: true,
        deptDesc: '第一線客戶回應與問題處理。',
        createTime: '2024-03-01T09:00:00',
        createUser: 'ops_mgr',
        updateTime: '2024-07-01T09:30:00',
        updateUser: 'ops_mgr',
        parentDeptName: '營運管理中心',
        managerName: '鄭佳珊'
    },
    {
        deptId: 8,
        parentDeptId: 3,
        deptCode: 'PROC',
        deptName: '採購組',
        deptLevel: 'LOB-S',
        managerEmpId: 8,
        isActive: true,
        deptDesc: '原物料與外包服務採購。',
        createTime: '2024-03-02T10:00:00',
        createUser: 'ops_mgr',
        updateTime: '2024-07-01T10:15:00',
        updateUser: 'ops_mgr',
        parentDeptName: '營運管理中心',
        managerName: '王柏廷'
    },
    {
        deptId: 9,
        parentDeptId: 4,
        deptCode: 'DOMS',
        deptName: '國內銷售組',
        deptLevel: 'LOB-S',
        managerEmpId: 9,
        isActive: true,
        deptDesc: '負責國內客戶與經銷商業務。',
        createTime: '2024-03-03T11:00:00',
        createUser: 'sale_mgr',
        updateTime: '2024-07-01T11:25:00',
        updateUser: 'sale_mgr',
        parentDeptName: '銷售服務中心',
        managerName: '林家宏'
    },
    {
        deptId: 10,
        parentDeptId: 4,
        deptCode: 'INTR',
        deptName: '國際銷售組',
        deptLevel: 'LOB-S',
        managerEmpId: 10,
        isActive: true,
        deptDesc: '拓展海外市場，協助出口業務。',
        createTime: '2024-03-04T12:00:00',
        createUser: 'sale_mgr',
        updateTime: '2024-07-01T12:35:00',
        updateUser: 'sale_mgr',
        parentDeptName: '銷售服務中心',
        managerName: '葉欣怡'
    },
    {
        deptId: 11,
        parentDeptId: 5,
        deptCode: 'DEV',
        deptName: '後端開發組',
        deptLevel: 'LOB-S',
        managerEmpId: 11,
        isActive: true,
        deptDesc: '專注於後端系統設計與維護。',
        createTime: '2024-03-05T13:00:00',
        createUser: 'eng_mgr',
        updateTime: '2024-07-01T13:45:00',
        updateUser: 'eng_mgr',
        parentDeptName: '工程研發中心',
        managerName: '曾國凱'
    },
    {
        deptId: 12,
        parentDeptId: 5,
        deptCode: 'FRONT',
        deptName: '前端開發組',
        deptLevel: 'LOB-S',
        managerEmpId: 12,
        isActive: true,
        deptDesc: '前端UI與互動介面設計。',
        createTime: '2024-03-06T14:00:00',
        createUser: 'eng_mgr',
        updateTime: '2024-07-01T14:55:00',
        updateUser: 'eng_mgr',
        parentDeptName: '工程研發中心',
        managerName: '陳韋廷'
    },
    {
        deptId: 13,
        parentDeptId: 6,
        deptCode: 'TEST',
        deptName: '軟體測試組',
        deptLevel: 'LOB-S',
        managerEmpId: 13,
        isActive: true,
        deptDesc: '產品測試與自動化回歸測試。',
        createTime: '2024-03-07T15:00:00',
        createUser: 'qa_mgr',
        updateTime: '2024-07-01T15:20:00',
        updateUser: 'qa_mgr',
        parentDeptName: '品質管理中心',
        managerName: '賴信瑋'
    },
    {
        deptId: 14,
        parentDeptId: 6,
        deptCode: 'CTRL',
        deptName: '品管稽核組',
        deptLevel: 'LOB-S',
        managerEmpId: 14,
        isActive: true,
        deptDesc: '協助品質稽核與標準作業稽查。',
        createTime: '2024-03-08T16:00:00',
        createUser: 'qa_mgr',
        updateTime: '2024-07-01T16:40:00',
        updateUser: 'qa_mgr',
        parentDeptName: '品質管理中心',
        managerName: '簡雅婷'
    },
    {
        deptId: 15,
        parentDeptId: 3,
        deptCode: 'RISK',
        deptName: '風險控管組',
        deptLevel: 'LOB-S',
        managerEmpId: 15,
        isActive: false,
        deptDesc: '內部稽核、企業風險評估與控管。',
        createTime: '2024-03-09T17:00:00',
        createUser: 'ops_mgr',
        updateTime: '2024-07-02T17:10:00',
        updateUser: 'ops_mgr',
        parentDeptName: '營運管理中心',
        managerName: '許榮華'
    },
    {
        deptId: 16,
        parentDeptId: 4,
        deptCode: 'MARK',
        deptName: '行銷推廣組',
        deptLevel: 'LOB-S',
        managerEmpId: 16,
        isActive: true,
        deptDesc: '產品推廣、品牌行銷與活動執行。',
        createTime: '2024-03-10T18:00:00',
        createUser: 'sale_mgr',
        updateTime: '2024-07-02T18:30:00',
        updateUser: 'sale_mgr',
        parentDeptName: '銷售服務中心',
        managerName: '葉姿君'
    },
    {
        deptId: 17,
        parentDeptId: 5,
        deptCode: 'UXUI',
        deptName: 'UX設計組',
        deptLevel: 'LOB-S',
        managerEmpId: 17,
        isActive: true,
        deptDesc: '使用者體驗與介面設計團隊。',
        createTime: '2024-03-11T19:00:00',
        createUser: 'eng_mgr',
        updateTime: '2024-07-02T19:10:00',
        updateUser: 'eng_mgr',
        parentDeptName: '工程研發中心',
        managerName: '鄧宜樺'
    },
    {
        deptId: 18,
        parentDeptId: 6,
        deptCode: 'SQA',
        deptName: '自動化測試組',
        deptLevel: 'LOB-S',
        managerEmpId: 18,
        isActive: true,
        deptDesc: '軟體測試自動化開發、測試效率提升。',
        createTime: '2024-03-12T20:00:00',
        createUser: 'qa_mgr',
        updateTime: '2024-07-02T20:10:00',
        updateUser: 'qa_mgr',
        parentDeptName: '品質管理中心',
        managerName: '方承睿'
    },
    {
        deptId: 19,
        parentDeptId: 5,
        deptCode: 'DOCS',
        deptName: '技術文件組',
        deptLevel: 'LOB-S',
        managerEmpId: 19,
        isActive: true,
        deptDesc: '撰寫、管理技術與開發文件。',
        createTime: '2024-03-13T21:00:00',
        createUser: 'eng_mgr',
        updateTime: '2024-07-02T21:10:00',
        updateUser: 'eng_mgr',
        parentDeptName: '工程研發中心',
        managerName: '廖立文'
    },
    {
        deptId: 20,
        parentDeptId: 3,
        deptCode: 'SUP',
        deptName: '支援服務組',
        deptLevel: 'LOB-S',
        managerEmpId: 20,
        isActive: true,
        deptDesc: '內部技術與行政支援服務窗口。',
        createTime: '2024-03-14T22:00:00',
        createUser: 'ops_mgr',
        updateTime: '2024-07-02T22:10:00',
        updateUser: 'ops_mgr',
        parentDeptName: '營運管理中心',
        managerName: '林品妤'
    }
];

